spring:
  profiles:
    active: dev
eureka:
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
    enabled: false
    fetch-registry: false
    register-with-eureka: false
  instance:
    preferIpAddress: true
springdoc:
  packages-to-scan: com.yes255.yes255booksusersserver.presentation.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /books/swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /books/v3/api-docs