spring:
  data:
    elasticsearch:
      username: elastic
      password: nhnacademy123!
      repositories:
        enabled: true
      url: 133.186.153.195:9200

  application:
    name: book-user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_book
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 10
      max-total: 10
      max-idle: 10
      min-idle: 10
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  file:
    path: ${user.home}/logs/${spring.application.name}
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8060
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/

jwt:
  secret: ${JWT_SECRET}
api:
  order-payment: ${ORDER_PAYMENT_SERVER}
  coupons: ${COUPON_SERVER}
  auth : http://133.186.153.195:8050