spring:
  data:
    elasticsearch:
      username: elastic
      password: nhnacademy123!
      repositories:
        enabled: true
      url: 133.186.153.195:9200

  application:
    name: book-user-server
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;MODE=MYSQL
#    username: sa
#    password: 1234
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_book
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
        initial-size: 10
        max-total: 10
        max-idle: 10
        min-idle: 10
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  file:
    path: ${user.dir}/logs/${spring.application.name}
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8061
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
api:
  order-payment: http://localhost:8071
  coupons: http://localhost:8081
  auth : http://localhost:8050
app:
  mode: development