spring:
  application:
    name: book-user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_book
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
  file:
    path: ${user.home}/logs/${spring.application.name}
server:
  port: 8060
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/

api:
  order-payment: ${ORDER_PAYMENT_SERVER}
  coupons: ${COUPON_SERVER}