spring:
  profiles:
    active: dev
eureka:
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
    enabled: false
    fetch-registry: false
    register-with-eureka: false
  instance:
    preferIpAddress: true